export const HTTPS_STATUS_OK = 200;
export const HTTPS_STATUS_NO_CONTENT = 204;
export const HTTPS_STATUS_CREATED= 201;
export const HTTPS_STATUS_INTERNAL_SERVER_ERROR = 500;
export const HTTPS_STATUS_UNAUTHORIZED = 401;
export const HTTPS_STATUS_BAD_REQUEST = 400;
export const HTTPS_STATUS_NOT_FOUND = 404;